AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
    - 'Rakefile'
    - 'db/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

  RunRailsCops: true

Style/WordArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: fals
